services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "9999:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: